# Generated by Django 6.0.4 on 2026-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_menuitem_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.CharField(default="Bangalore", max_length=100),
        ),
    ]
